import Header from "./components/Header";
import "./globals.css";
import { UserContextProvider } from "./utils/UserContext";
import { useUser } from "./utils/useUser";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const user = await useUser();
  return (
    <UserContextProvider value={user}>
      <html lang="en">
        <body className="bg-gray-very-light">
          <Header user={user} />
          {children}
        </body>
      </html>
    </UserContextProvider>
  );
}
